name: "Kubernetes Deploy"
description: "Deploy application to Kubernetes cluster"

inputs:
  environment:
    description: "Deployment environment"
    required: true
  app-name:
    description: "Application name"
    required: true
  image:
    description: "Docker image to deploy"
    required: true
  namespace:
    description: "Kubernetes namespace"
    required: true
  aks-cluster-name:
    description: "AKS cluster name"
    required: false
    default: ""
  aks-resource-group:
    description: "AKS resource group"
    required: false
    default: ""
  azure-client-id:
    description: "Azure Client ID"
    required: true
  azure-tenant-id:
    description: "Azure Tenant ID"
    required: true
  azure-subscription-id:
    description: "Azure Subscription ID"
    required: true
  github-token:
    description: "GitHub token for tagging"
    required: true

runs:
  using: "composite"
  steps:
    - name: "Login via Azure CLI"
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    - name: "Create kubeconfig file"
      shell: bash
      run: |
        az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing
        kubelogin convert-kubeconfig -l azurecli
      env:
        AKS_CLUSTER_NAME: ${{ inputs.aks-cluster-name }}
        AKS_RESOURCE_GROUP: ${{ inputs.aks-resource-group }}

    - name: Update image
      shell: bash
      run: |
        kubectl set image deployment/$APP_NAME $APP_NAME=$IMAGE -n $K8S_NAMESPACE
        kubectl rollout status deployment/$APP_NAME -n $K8S_NAMESPACE --timeout=300s
      env:
        K8S_NAMESPACE: ${{ inputs.namespace }}
        APP_NAME: ${{ inputs.app-name }}
        IMAGE: ${{ inputs.image }}

    - name: Remove old deployment tag
      shell: bash
      run: |
        git push --delete origin "$ENVIRONMENT-$VERSION_TAG" || echo "Failed to delete tag, but continuing anyway."
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        VERSION_TAG: ${{ inputs.app-name }}
      continue-on-error: true

    - name: Tag deployment
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ inputs.github-token }}
        custom_tag: "${{ inputs.environment}}-${{ inputs.app-name}}"
        release_branches: "main"
        tag_prefix: ""
      continue-on-error: true
