name: components-gateway
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/components-gateway.yml"
      - "src/components/gateway/**"
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/components-gateway.yml"
      - "src/components/gateway/**"

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-tag:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version-tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: version-tag
        uses: ./.github/actions/version-tag
        with:
          prefix: "gateway"
          github-token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: [version-tag]
    uses: ./.github/workflows/template-docker.yml
    with:
      dockerfile: src/components/gateway/Dockerfile
      working-directory: src/components/gateway
      image_name: m8thubinfraweacr.azurecr.io/gateway
      version: ${{ needs.version-tag.outputs.version }}
    secrets: inherit

  deploy:
    needs: [version-tag, docker]
    strategy:
      fail-fast: false
      matrix:
        env: [
          { name: "dev-app", infra: "stg-infra"},
          { name: "prd-app", infra: "stg-infra"}
        ]
    uses: ./.github/workflows/template-k8s-deploy.yml
    with:
      environment: ${{ matrix.env.name }}
      namespace: "m8t-${{ matrix.env.name }}"
      app-name: "gateway"
      image: ${{ needs.docker.outputs.image_name }}
      aks-cluster-name: "m8t-aks"
      aks-resource-group: "m8t-${{ matrix.env.infra }}-we-aks"    
    secrets: inherit