name: docker-build-github-actions-runner
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker-build-github-actions-runner.yml"
      - "docker/docker-file/github-actions-runner/**"
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/docker-build-github-actions-runner.yml"
      - "docker/docker-file/github-actions-runner/**"
  schedule:
    - cron: '0 2 * * 0'  # Every sunday at 02:00 UTC

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  docker:
    uses: ./.github/workflows/template-docker.yml
    with:
      dockerfile: docker/docker-file/github-actions-runner/Dockerfile
      working-directory: docker/docker-file/github-actions-runner
      image_name: m8thubinfraweacr.azurecr.io/github-actions-runner
      version: 2025-1
    secrets: inherit
