name: docker-build-blankapp
on:
  push:
    branches:
      - main
    paths:
      - "docker/docker-file/blankapp/**"
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "docker/docker-file//blankapp/**"

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  version-tag:
    runs-on: ubuntu-24.04
    outputs:
      version: ${{ steps.version-tag.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        id: version-tag
        uses: ./.github/actions/version-tag
        with:
          prefix: blankapp
          github-token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    needs: [version-tag]
    runs-on: ubuntu-24.04
    environment: build
    outputs:
      image_name: ${{ steps.docker-build.outputs.image_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        id: docker-build
        uses: ./.github/actions/docker
        with:
          dockerfile: docker/docker-file/blankapp/Dockerfile
          working-directory: docker/docker-file/blankapp
          image_name: m8thubinfraweacr.azurecr.io/blankapp
          version: ${{ needs.version-tag.outputs.version }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
