name: docker-build-github-actions-runner
on:
  push:
    branches:
      - main
    paths:
      - "docker/docker-file/github-actions-runner/**"
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "docker/docker-file/github-actions-runner/**"
  schedule:
    - cron: '0 2 * * 0'  # Every sunday at 02:00 UTC

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  docker:
    runs-on: ubuntu-24.04
    environment: build
    outputs:
      image_name: ${{ steps.docker-build.outputs.image_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push Docker image
        id: docker-build
        uses: ./.github/actions/docker
        with:
          dockerfile: docker/docker-file/github-actions-runner/Dockerfile
          working-directory: docker/docker-file/github-actions-runner
          image_name: m8thubinfraweacr.azurecr.io/github-actions-runner
          version: 2025-1
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
