name: infra-az-spoke-resources

on:
  push:
    branches:
      - main
    paths:
      - "infra/az-spoke-resources/**"
      - ".github/workflows/infra-az-spoke-resources.yml"
  pull_request:
    paths:
      - "infra/az-spoke-resources/**"
      - ".github/workflows/infra-az-spoke-resources.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  terraform:
    strategy:
      fail-fast: false
      matrix:
        env: [{ name: "stg-infra" }]
    uses: ./.github/workflows/template-terraform.yml
    with:
      working-dir: "infra/az-spoke-resources"
      environment: ${{ matrix.env.name }}
      backend-key: "az-spoke-resources"
      vars: |
        azure_subscription_id
        azure_tenant_id
      private-runner: "arc-${{ matrix.env.name }}-runners"
    secrets: inherit