name: infra-k8s-devops

on:
  push:
    branches:
      - main
    paths:
      - "infra/k8s-devops/**"
      - ".github/workflows/infra-k8s-devops.yml"
  pull_request:
    paths:
      - "infra/k8s-devops/**"
      - ".github/workflows/infra-k8s-devops.yml"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  terraform:
    strategy:
      fail-fast: false
      matrix:
        env: [{ name: "stg-infra" }]
    uses: ./.github/workflows/template-terraform.yml
    with:
      working-dir: "infra/k8s-devops"
      environment: ${{ matrix.env.name }}
      backend-key: "k8s-devops"
      aks-cluster-name: "m8t-aks"
      aks-resource-group: "m8t-${{ matrix.env.name }}-we-aks"      
      vars: |
        azure_subscription_id
        azure_tenant_id
        gh_runner_app_id
        gh_runner_app_installation_id
        gh_runner_app_private_key
      private-runner: "arc-${{ matrix.env.name }}-runners"
    secrets: inherit