name: template-k8s-deploy

on:
    workflow_call:
      inputs:
        environment:
          required: true
          type: string
        app-name:
          required: true
          type: string
        image:
          required: true
          type: string
        namespace:
          required: true
          type: string
        private-runner:
          required: false
          type: string
        aks-cluster-name:
          required: false
          type: string
        aks-resource-group:
          required: false
          type: string

permissions:
  contents: write
  id-token: write
  
jobs:
  k8s-deploy-image:
    environment: ${{ inputs.environment }}
    runs-on: ${{ inputs.private-runner }}
    steps:

    - name: "Login via Azure CLI"
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - id: kubeconfig
      name: "Create kubeconfig file"
      run: |
          az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing
          kubelogin convert-kubeconfig -l azurecli
      env:
        AKS_CLUSTER_NAME: ${{ inputs.aks-cluster-name }}
        AKS_RESOURCE_GROUP: ${{ inputs.aks-resource-group }}

    - name: Update image
      run: |
        kubectl set image deployment/$APP_NAME $APP_NAME=$IMAGE -n $K8S_NAMESPACE
        kubectl rollout status deployment/$APP_NAME -n $K8S_NAMESPACE --timeout=300s
      env:
        K8S_NAMESPACE: ${{ inputs.namespace }}
        APP_NAME: ${{ inputs.app-name }}
        IMAGE: ${{ inputs.image }}

  tag:
    needs: k8s-deploy-image
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Remove old deployment tag
      run: |
        git push --delete origin "$ENVIRONMENT-$VERSION_TAG" || echo "Failed to delete tag, but continuing anyway."
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        VERSION_TAG: ${{ inputs.app-name }}
      continue-on-error: true
        
    - name: Tag deployment
      uses: mathieudutour/github-tag-action@v6.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        custom_tag:  "${{ inputs.environment}}-${{ inputs.app-name}}"
        release_branches: "main"
        tag_prefix: ""
      continue-on-error: true