name: template-terraform

on:
  workflow_call:
    inputs:
      working-dir:
        required: true
        type: string
      environment:
        required: false
        type: string
      backend-key:
        required: true
        type: string
      aks-cluster-name:
        required: false
        type: string
        default: ""
      aks-resource-group:
        required: false
        type: string
        default: ""
      vars:
        required: false
        type: string
        default: ''
      private-runner:
        required: false
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write

env:
  TF_BACKEND_KEY: ${{ inputs.backend-key }}
  TF_VAR_env: ${{ inputs.environment }}
  ENVIRONMENT: ${{ inputs.environment }}
  ARM_USE_OIDC: "true"

jobs:

  setup:
    runs-on: ubuntu-24.04
    outputs:
      runner-config: ${{ steps.determine-config.outputs.runner-config }}
    steps:
    - name: Determine runs-on config
      id: determine-config
      run: |
        if [ "$PRIVATE_RUNNER" == "true" ]; then
          echo "Using custom configuration"
          labels=$(echo "\"${ENVIRONMENT}\", \"m8t\"")
          runner_desc=$(echo "{\"labels\":[$labels]}") 
          config=$(echo $runner_desc | jq -c '.')
          echo "runner-config=$config"
          echo "runner-config=$config" >> $GITHUB_OUTPUT
        else
          echo "Using ubuntu-24.04"
          echo "runner-config=ubuntu-24.04" >> $GITHUB_OUTPUT
        fi
      env:
        PRIVATE_RUNNER: ${{ inputs.private-runner }}
        REPO_ENV: ${{ inputs.environment }}

  analyze:
    runs-on: ubuntu-24.04
    environment: plan-${{ inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID  }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'
          terraform_wrapper: false

      - name: Terraform Fmt
        run: terraform fmt -recursive -check
        working-directory: ${{ inputs.working-dir }}
        
      - name: Init
        run: terraform init -backend-config key=$TF_BACKEND_KEY-$ENVIRONMENT.tfstate -backend-config subscription_id=$ARM_SUBSCRIPTION_ID -upgrade
        working-directory: ${{ inputs.working-dir }}

      - name: Validate
        run: terraform validate
        working-directory: ${{ inputs.working-dir }}

      - name: Check terraform with Checkov
        id: checkov
        uses: using-system/devops/github/actions/checkov@main
        with:
          working-directory:  ${{ inputs.working-dir }}

          
  plan:
    environment: plan-${{ inputs.environment }}
    needs: [ setup, analyze]
    runs-on: ${{ needs.setup.outputs.runner-config == 'ubuntu-24.04' && 'ubuntu-24.04' || fromJson(needs.setup.outputs.runner-config) }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID  }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Azure CLI
        if: ${{ inputs.private-runner}}
        run: |
         curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash        

      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - id: kubeconfig
        if: ${{ inputs.aks-cluster-name != '' && inputs.aks-resource-group != '' }}
        name: "Create kubeconfig file"
        run: |
          az aks install-cli
          az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing
          kubelogin convert-kubeconfig -l azurecli
          echo "TF_VAR_aks_cluster_name=${AKS_CLUSTER_NAME}" >> $GITHUB_ENV
          echo "TF_VAR_aks_resource_group_name=${AKS_RESOURCE_GROUP}" >> $GITHUB_ENV
        env:
            AKS_CLUSTER_NAME: ${{ inputs.aks-cluster-name }}
            AKS_RESOURCE_GROUP: ${{ inputs.aks-resource-group }}          

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'
          terraform_wrapper: true
      - name: Set up Node.js
        if: ${{ inputs.private-runner}}
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Init
        run: terraform init -backend-config key=$TF_BACKEND_KEY-$ENVIRONMENT.tfstate -backend-config subscription_id=$ARM_SUBSCRIPTION_ID -upgrade
        working-directory: ${{ inputs.working-dir }}

      - run: |
          for key in $(echo $KEYS  | tr "," "\n"); do
            SECRET_KEY=`echo $key | tr '[:lower:]' '[:upper:]'`
            VAL=`jq -r ".${SECRET_KEY}" <<< $SECRETS`
            if (( $(grep -c . <<<"${VAL}") > 1 )); then
              #VAL has more than one line
              echo "TF_VAR_${key}<<EOF" >> $GITHUB_ENV
              echo ${VAL} >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
              echo "${key}<<EOF" >> $GITHUB_ENV
              echo ${VAL} >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
            else
              #VAL has at most one line
              echo "TF_VAR_${key}=${VAL}" >> $GITHUB_ENV
              echo "${key}=${VAL}" >> $GITHUB_ENV
            fi
          done
        env:
          KEYS: ${{ inputs.vars }}
          SECRETS: ${{ toJSON(secrets) }}

      - name: Plan
        id: plan
        run: |
          terraform plan -out=tfplan -var-file="vars/${ENVIRONMENT}.tfvars" -detailed-exitcode | tee plan_output.txt

          PLAN_EXIT_CODE=${PIPESTATUS[0]}
          if [ $PLAN_EXIT_CODE -ne 0 ]; then
            echo "Terraform plan failed with exit code $PLAN_EXIT_CODE."
            exit 1
          fi
          
          if grep -q "Infrastructure is up-to-date." plan_output.txt; then
            echo "changes=false" >> "$GITHUB_OUTPUT"
          elif grep -q "Your infrastructure matches the configuration." plan_output.txt; then
            echo "changes=false" >> "$GITHUB_OUTPUT"
          elif grep -q "Plan:" plan_output.txt; then
            echo "changes=true" >> "$GITHUB_OUTPUT"
          else
            exit 1
          fi
        working-directory: ${{ inputs.working-dir }}

      - name: Upload tfplan as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ inputs.environment }}
          path: |
            ${{ inputs.working-dir }}/tfplan

    outputs:
      changes: ${{ steps.plan.outputs.changes }}

  apply:
    needs: [ setup, plan]
    runs-on: ${{ needs.setup.outputs.runner-config == 'ubuntu-24.04' && 'ubuntu-24.04' || fromJson(needs.setup.outputs.runner-config) }}
    if: needs.plan.outputs.changes == 'true'
    environment: ${{ inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID  }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install Azure CLI
        if: ${{ inputs.private-runner}}
        run: |
         curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash           

      - name: "Login via Azure CLI"
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - id: kubeconfig
        if: ${{ inputs.aks-cluster-name != '' && inputs.aks-resource-group != '' }}
        name: "Create kubeconfig file"
        run: |
          az aks install-cli
          az aks get-credentials --resource-group $AKS_RESOURCE_GROUP --name $AKS_CLUSTER_NAME --overwrite-existing
          kubelogin convert-kubeconfig -l azurecli
        env:
            AKS_CLUSTER_NAME: ${{ inputs.aks-cluster-name }}
            AKS_RESOURCE_GROUP: ${{ inputs.aks-resource-group }}          

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 'latest'
          terraform_wrapper: true
      - name: Set up Node.js
        if: ${{ inputs.private-runner}}
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Init
        run: terraform init -backend-config key=$TF_BACKEND_KEY-$ENVIRONMENT.tfstate -backend-config subscription_id=$ARM_SUBSCRIPTION_ID -upgrade
        working-directory: ${{ inputs.working-dir }}

      - name: Download tfplan artifact
        uses: actions/download-artifact@v4
        with:
          name: "tfplan-${{ inputs.environment }}"
          path: ${{ inputs.working-dir }}

      - name: Terraform Apply
        run: terraform apply 'tfplan'
        working-directory: ${{ inputs.working-dir }}