name: "Calculate Modified Directories"
description: "Determines which directories have been modified in a PR"

inputs:
  base-directory:
    description: "Base working directory to scan for modifications"
    required: true

outputs:
  modified_directories:
    description: "JSON array of modified directories"
    value: ${{ steps.process-changed-files.outputs.final_directories }}

runs:
  using: "composite"
  steps:
    - name: Calculate directory depth
      id: calculate-depth
      shell: bash
      run: |
        # Count the number of directory separators in the path and add 1
        DEPTH=$(echo "${{ inputs.base-directory }}" | awk -F'/' '{print NF+1}')
        echo "Directory depth: $DEPTH"
        echo "depth=$DEPTH" >> $GITHUB_OUTPUT

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@2f7c5bfce28377bc069a65ba478de0a74aa0ca32
      with:
        json: true
        quotepath: false
        escape_json: false
        dir_names: "true"
        files: ${{ inputs.base-directory }}/**
        dir_names_max_depth: ${{ steps.calculate-depth.outputs.depth }}

    - name: List all changed files
      shell: bash
      run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

    - name: Process changed files
      id: process-changed-files
      shell: bash
      run: |
        CHANGED_FILES='${{ steps.changed-files.outputs.all_changed_files }}'

        # Check if there are any changed files
        if [ "$CHANGED_FILES" == "[]" ] || [ -z "$CHANGED_FILES" ]; then
          echo "No modified directories found. Setting empty array as default."
          # Set an empty array as the default value
          echo "final_directories=[]" >> $GITHUB_OUTPUT
        else
          # Filter out specific directories (modules for infra, etc.) and the root directory
          FILTERED_DIRECTORIES=$(echo "$CHANGED_FILES" | jq -c '[.[] | select(. != "${{ inputs.base-directory }}/modules" and . != "${{ inputs.base-directory }}")]')
          echo "Original changed files: $CHANGED_FILES"
          echo "Filtered directories (excluding modules and root): $FILTERED_DIRECTORIES"
          echo "final_directories=$FILTERED_DIRECTORIES" >> $GITHUB_OUTPUT
        fi
